'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.meteochile.cl/reg07.html")>  _
        Public ReadOnly Property ConnInternet() As String
            Get
                Return CType(Me("ConnInternet"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vivero D&D")>  _
        Public ReadOnly Property DatEmpIDM() As String
            Get
                Return CType(Me("DatEmpIDM"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vivero D&D")>  _
        Public Property DatEmpLAD() As String
            Get
                Return CType(Me("DatEmpLAD"),String)
            End Get
            Set
                Me("DatEmpLAD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vivero XXXXXXXXXXXXXXXXXX")>  _
        Public Property DatEmpDESA() As String
            Get
                Return CType(Me("DatEmpDESA"),String)
            End Get
            Set
                Me("DatEmpDESA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fono +569 7991 1499")>  _
        Public Property DatEMPLADFono() As String
            Get
                Return CType(Me("DatEMPLADFono"),String)
            End Get
            Set
                Me("DatEMPLADFono") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fono +569 6864 3597")>  _
        Public Property DatEmpIDMFono() As String
            Get
                Return CType(Me("DatEmpIDMFono"),String)
            End Get
            Set
                Me("DatEmpIDMFono") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vivero D&D")>  _
        Public Property DataEmp() As String
            Get
                Return CType(Me("DataEmp"),String)
            End Get
            Set
                Me("DataEmp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fono +569 7991 1499")>  _
        Public Property DataFono() As String
            Get
                Return CType(Me("DataFono"),String)
            End Get
            Set
                Me("DataFono") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fono +569 7991 1499")>  _
        Public Property DataEmpDESAFono() As String
            Get
                Return CType(Me("DataEmpDESAFono"),String)
            End Get
            Set
                Me("DataEmpDESAFono") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("d:\")>  _
        Public Property Dir_Ficha() As String
            Get
                Return CType(Me("Dir_Ficha"),String)
            End Get
            Set
                Me("Dir_Ficha") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MIPC;Initial Catalog=GEST;Integrated Security=True")>  _
        Public Property R_NBLocal() As String
            Get
                Return CType(Me("R_NBLocal"),String)
            End Get
            Set
                Me("R_NBLocal") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=72.60.59.142;Initial Catalog=ddvivero;User ID=vivero_user;Password=sq"& _ 
            "L_2025!###;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property ConexionVivero() As String
            Get
                Return CType(Me("ConexionVivero"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VIVERO D&D")>  _
        Public Property Sistema() As String
            Get
                Return CType(Me("Sistema"),String)
            End Get
            Set
                Me("Sistema") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=72.60.59.142;Initial Catalog=ddvivero;User ID=vivero_user;Password=sq"& _ 
            "L_2025!###;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SettingPrueba() As String
            Get
                Return CType(Me("SettingPrueba"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MIPC\SQLEXPRESS;Initial Catalog=ddvivero;Integrated Security=True;Tru"& _ 
            "stServerCertificate=True")>  _
        Public ReadOnly Property DBLocal() As String
            Get
                Return CType(Me("DBLocal"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GestionVivero.My.MySettings
            Get
                Return Global.GestionVivero.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
